# coding=utf-8
############################################################
#Nombre del archivo: cuboSemantico.py
#Autores: 
# Ricardo Licea Mata A01280892
# Miguel Bazan Aviña A01281010
#
#Función del archivo:
#Este archivo, recibe en sus funciones 3 variables, los 
# cuales corresponderan a los tipos de datos involucrados en 
#alguna operación y al operador en si. Dependiento los tipos de datos, 
# y el operador, regresa el valor de retorno que deberia de tener dicha operación
#o en su caso, una Key de error especificando que la operación entre esos tipos de datos
#no es posible.
#
#############################################################


cuboSemantico = {
    "int": {
        "int": {
            "+":"int", 
            "-":"int", 
            "*":"int", 
            "/":"int", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"int",
            "==": "bool", 
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"int", 
            "==": "bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==": "Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==": "Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
    "float":{
        "int": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"float",
            "==": "bool", 
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"float", 
            "==": "bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error",
            "==":"Error", 
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error",
            "==":"Error", 
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
    "bool":{
        "int": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"bool", 
            "==":"bool",
            "<>":"bool",
            "and":"bool", 
            "or":"bool",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    },
    "string":{
        "int": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"string", 
            "==":"bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
}